easyQuestions = [
  "How to read a matrix from console in java?",
  "How to remove duplicates from string in java?",
  "Write a java program to duplicate characters with number of occurences in java?",
  "Write a java program to implement bubble sort part 1?",
  "Write a java program to check string is palindrome or not?",
  "Write a java program to print floyds triangle?",
  "Write a java program to print floyds triangle?",
  "How to count number of vowels in a string in java?",
  "How to find largest and smallest values in an array in java?",
  "Write java program to find duplicate elements in array in java?",
  "write a java program to check the input number is prime or not in java?",
  "Write a java program to print pyramid pattern of numbers?",
  "Write a java program to find missing number in array in java?",
  "Write a java program  to print numbers in java up to 10 with out using loops?",
  "How to sort elements in array in asc and desc order in java?",
  "Write a java program to find factorial of a number in java?",
  "write a java program to find second largest element in the array in the java?",
  "Write a java program to check two Strings are anagrams or not by sorting and comparing strings?",
  "Write java program to print Characters count in each word in String ?",
  "Write a java program to find reverse of a string in java?",
  "Write a java program to add elements in an array in java?",
  "Write a java program to find largest of three numbers?",
  "Write a java program to print multiplication table?",
  "Write a java program to print star pattern?",
  "Write a java program to find factors of number from 1 to 100",
  "Write a java program to print fibonacci series using loops?",
  "Write a java program to print Ascii values of a Character ?",
  "write a java program to implement bubble sort - Part 2?",
  "Write a java program to print fibonacci series ?",
  "Write a java program to sort characters in String in java?",
  "How to sort hashmap keys in java?",
  "Write a java program to check two strings are anagrams or not?",
  "Write a java program to find factorial for large number?",
  "Write a java program to find even and odd number?",
  "How to Swap two numbers without using third variable in java?(Addition and subtraction operation)",
  "Write a java program to convert Fahrenheit to celsius?",
  "Write a java program to find reverse of a number in java?",
  "Write a java program to print alphabets?",
  "Write a java program to check given input character is alphabet or not ?",
  "How to reverse the order of elements in arraylist in java?",
  "How to swap elements in list in java",
  "Write a java program to find sum of 10 numbers in java?",
  "How to swap two numbers in java?",
  "How to swap two numbers in java with out using temp variable?",
  "Write a java program to check whether array contains duplicates?",
  "How to calculate area of Rectangle in java?",
  "Write a java program to find factorial of a number recursion?",
  "How to calculate area and circumference of a circle in java?",
  "How to delete element from array in java?",
];
